version: '3'
services:
  app:
    container_name: listaRangoServer
    restart: always
    build: .
    ports:
      - '3000:3000'
    links:
      - mongo
  mongo:
    container_name: listaRangoDB
    image: mongo:4.2.3
    ports:
      - '27017:27017'
